version: '3.5'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4.13-alpine
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./input_data:/csv_files
      - ./docker-entrypoint-initdb.d/00_initial_datasets_tables.sh:/docker-entrypoint-initdb.d/00_initial_datasets_tables.sh
    entrypoint: /bin/sh -c "chmod +x /docker-entrypoint-initdb.d/00_initial_datasets_tables.sh && /entrypoint.sh"

  solution:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: solution
    depends_on:
      - clickhouse
    volumes:
      - ./data:/app/data  
      - ./entrypoint.sh:/entrypoint.sh  
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
    entrypoint: ["/entrypoint.sh"]  

#  solution:
#    image: solution
#    depends_on:
#      - clickhouse
#    ...